devices([
   "iPhone X",
   "iPhone 8 Plus",
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme "Wabbit"

# Where should the resulting screenshots be stored?
output_directory "fastlane/screenshots"

clear_previous_screenshots true

# Choose which project/workspace to use
# project "./Wabbit.xcodeproj"
# workspace "./Wabbit.xcworkspace"

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
# ios_version '11.1'
